version: '2.27.0'

services:

  tags-management-db:
    image: mongo
    container_name: tags-management-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tags-management-service
      - MONGO_INITDB_ROOT_PASSWORD=tags-management-service
      - MONGO_INITDB_DATABASE=tags-management-service
      - TZ=America/Sao_Paulo
    ports:
      - 27017:27017

volumes:
  tag-management-data: