version: '2.27.0'

services:

  tags-management-db:
    image: mongo
    container_name: tags-management-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tags-management-service
      - MONGO_INITDB_ROOT_PASSWORD=tags-management-service
      - MONGO_INITDB_DATABASE=tags-management-service
      - TZ=America/Sao_Paulo
    ports:
      - 27017:27017

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
volumes:
  tag-management-data: