server:
  port: 7000

spring:
  application:
    name: tags-management-service
  mvc:
    static-path-pattern: /swagger*
  data:
    mongodb:
      uri: ${MONGO_DATABASE_URI:mongodb://tags-management-service:tags-management-service@localhost:27017/}
      database: ${MONGO_DATABASE_DATABASE:admin}

springdoc:
  swagger-ui:
    path: /docs

mongock:
  migration-scan-package:
    - com.leaseforlove.tagsmanagementservice.infraestructure.storage.migrations

app:
  queue:
    tags-registered-queue: ${TAGS_REGISTERED_QUEUE}